import Head from 'next/head'
import Nav from '../components/Nav'

export default function user() {
  return (
    <div>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      </div>
  )
}